### ISSUE TITLE
RipeRedis is not connecting to redis

### ISSUE THREAD

**Issue by ferozewaris** [iph0/AnyEvent-RipeRedis#1]
Hi, 

I am connecting Redis in my perl code through AnyEvent::RipeRedis module but it seems like it is not connecting. my sample code for connection is as follows. 
<pre>
                        my $status = 0;
                        my $conn = AnyEvent::RipeRedis->new(
                                host => 'localhost',
                                port=> 6379,
                                reconnect_interval => 10,
                                on_connect => sub {
                                        $status = 1;
                                        print "on_connect dunction"
                                },
                                on_disconnect => sub {
                                        $status = 2;
                                        print "on_disconnect function"
                                },
                                on_error => sub {
                                        my $err = shift;
                                        print "Error connecting radius Error->$err";
                                        $status = 2;
                                },

                        );
</pre>
Kindly Have a look on it. Tell me if i am doing it a wrong way.

**Comment by iph0** [comment]
Hello.

You must use event loop for connection and other operations via the client.

```perl
#!/usr/bin/env perl

use strict;
use warnings;

use AnyEvent::RipeRedis;
use AnyEvent;

my $cv = AE::cv;

my $redis = AnyEvent::RipeRedis->new(
  host               => 'localhost',
  port               => 6379,
  reconnect_interval => 10, 
  on_connect         => sub {
    print "on_connect function\n";
  },  
  on_disconnect => sub {
    print "on_disconnect function\n";
  },  
  on_error => sub {
    my $err = shift;
    print $err->messge;
  },  
);

$redis->ping(
  sub {
    my $reply = shift;
    my $err   = shift;

    if ( defined $err ) { 
      warn $err->message;
      $cv->send;

      return;
    }   

    print "$reply\n";
    $cv->send;

    return;
  }
);

$cv->recv;
```
